name: Bug Report
description: Report a bug or unexpected behavior in Quickstart Shops.
title: "[BUG]: "
labels: [ "bug" ]
assignees:
  - sebastianbingham

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report

        Please fill out the form below to report a bug in the Quickstart Shops module.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug or unexpected behavior you encountered.
      placeholder: Describe the problem, error message, or unexpected behavior here.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to help reproduce the issue.
      placeholder: |
        1. Go to...
        2. Click on...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: e.g. I expected the shop to load all default items without errors.
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the Quickstart Shops module are you using?
      options:
        - v25.03.230514
        - Older Version
    validations:
      required: true