name: Add/Delete/Change Item In Shop
description: Request to update items in a Quickstart Shop journal.
labels: [requested-shop-change]
assignees:
  - sebastianbingham
body:
  - type: markdown
    attributes:
      value: |
        ## 🛍️ Quickstart Shop Item Change Request

        Please use this form to request adding, removing, or updating the quantity of an item in a Quickstart Shop.

  - type: input
    id: item
    attributes:
      label: Item Name
      placeholder: e.g. Potion of Healing
    validations:
      required: true

  - type: number
    id: quantity
    attributes:
      label: Quantity
      description: Use 0 to request removal.
      placeholder: e.g. 3
    validations:
      required: true
