name: Add/Delete/Change Item In Shop
description: Request an item change in a Quickstart Shop journal.
title: "[Shop Change]: "
labels: ["requested-shop-change"]
assignees:
  - sebastianbingham

body:
  - type: markdown
    attributes:
      value: |
        🛍️ **Quickstart Shop Change Request**

        This form is only for requesting that an item be added, removed, or its quantity changed in a Quickstart Shop journal.

        **Note:**
        - This does **not** affect shops already imported into worlds.
        - This is a **request**, not a guarantee.
        - Please provide a reasonable justification.

  - type: input
    id: documentUUID
    attributes:
      label: Document UUID
      description: Found by clicking the globe/book icon on the journal entry in Foundry.
      placeholder: e.g. JournalEntry.quickstart-shop-name
    validations:
      required: true

  - type: input
    id: itemName
    attributes:
      label: Item Name
      description: The name of the item to add/remove/change.
      placeholder: e.g. Potion of Healing
    validations:
      required: true

  - type: number
    id: quantity
    attributes:
      label: Quantity
      description: Enter 0 to request removal.
      placeholder: e.g. 3
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Quickstart Shop Version
      description: What version are you using?
      options:
        - v25.03.230514
        - Older Version
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why should this change be made?
      description: Explain your reasoning for the item addition, removal, or change.
      placeholder: e.g. This item fits the theme of the apothecary better than X.
    validations:
      required: true
