name: Add/Delete/Change Item In Shop
description: Request to add, remove, or update the quantity of an item in a Quickstart Shop journal.
title: "[CHANGE-REQUEST]: "
labels: [ "requested-shop-change" ]
assignees:
  - sebastianbingham
body:
  - type: markdown
    attributes:
      value: |
        ## 🛍️ Thank you for your suggestion!

        This form is **only for requesting an item be added, removed, or its quantity changed** in a specific **Quickstart Shop** journal.

        📝 **Note**:
        - This **does not** affect shops that have already been imported into a world.
        - This is a change **request**, not a guarantee.
        - Please provide a clear rationale for the change—there are no hard rules yet, but we value thoughtful feedback.

  - type: input
    id: documentUUID
    attributes:
      label: Document UUID
      description: |
        The UUID of the shop journal entry. You can find it by clicking the book icon with the globe in the upper-left of the journal header.
      placeholder: "e.g. JournalEntry.quickstart-shop-name"
    validations:
      required: true

  - type: input
    id: itemName
    attributes:
      label: Item Name
      description: The exact name of the item you are requesting a change for.
      placeholder: "e.g. Potion of Healing"
    validations:
      required: true

  - type: input
    id: quantity
    attributes:
      label: Quantity
      description: What should the new quantity be? (Use 0 to remove an item.)
      placeholder: "e.g. 3"
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Why should this change be made?
      description: Provide a reasonable case for why this item should be added, removed, or changed.
      placeholder: "Explain why this item should be adjusted in the shop..."
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the Quickstart Shops module are you using?
      options:
        - v25.03.230514
        - Older Version
    validations:
      required: true
