blank_issues_enabled: false
contact_links:
  - name: 💬 General Questions or Help
    url: https://github.com/sebastianbingham/quickstart-shops/discussions
    about: Please use GitHub Discussions for general help, ideas, or non-shop-specific questions.
