name: Release to Foundry

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest release version
        id: get_version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create JSON payload
        id: create_payload
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          echo "Using version: $VERSION"

          echo '{
            "id": "quickstart-shops",
            "dry-run": true,
            "release": {
              "version": "'"$VERSION"'",
              "manifest": "https://github.com/${{ github.repository }}/releases/latest/download/module.json",
              "notes": "",
              "compatibility": {
                "minimum": "12",
                "verified": "12",
                "maximum": ""
              }
            }
          }' > payload.json

      - name: Send release to FoundryVTT API
        run: |
          RESPONSE=$(curl -s -X POST https://api.foundryvtt.com/_api/packages/release_version/ \
            -H "Content-Type: application/json" \
            -H "Authorization: ${{ secrets.PACKAGE_RELEASE_TOKEN }}" \
            --data @payload.json)

          echo "Foundry API Response:"
          echo "$RESPONSE"
          echo "$RESPONSE" > foundry-response.json
