name: Release to Foundry

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest release version
        id: get_version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Release Foundry Package
        id: release_foundry_package
        env:
          TOKEN: ${{ secrets.PACKAGE_RELEASE_TOKEN }}
        run: |
          cat << EOF > payload.json
          {
            "id": "quickstart-shops",
            "release": {
              "version": "${{ steps.get_version.outputs.version }}",
              "manifest": "https://github.com/sebastianbingham/quickstart-shops/releases/latest/download/module.json",
              "download": "$https://github.com/sebastianbingham/quickstart-shops/releases/latest/download/module.zip",
              "notes": "https://github.com/sebastianbingham/quickstart-shops/releases/tag/${{ steps.get_version.outputs.version }}",
              "compatibility": {
                "minimum": "12",
                "verified": "12",
                "maximum": ""
              }
            }
          }
          EOF

          cat payload.json  # Debug: Print the payload

          curl -X POST "https://api.foundryvtt.com/_api/packages/release_version" \
            -H "Content-Type: application/json" \
            -H "Authorization: $TOKEN" \
            -d @payload.json